# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# platform :ios, min_ios_version_supported
# prepare_react_native_project!

# # ❌ QUITA ESTO:
# # use_modular_headers!

# # ✅ Fuerza frameworks estáticos (no dependas de la variable de entorno)
# use_frameworks! :linkage => :static

# target 'QRiderRD' do
#   config = use_native_modules!

# use_react_native!(
#   :path => config[:reactNativePath],
#   :app_path => "#{Pod::Config.instance.installation_root}/..",
#   :new_arch_enabled => false,   # 👈 fuerza desactivar New Architecture
#   :fabric_enabled => false      # 👈 opcional pero recomendable, explícito
# )


#   pod 'GoogleSignIn'
  
#   post_install do |installer|
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false,
#       # :ccache_enabled => true
#     )

#     # Permite que los pods construidos como frameworks incluyan headers no modulares
#     installer.pods_project.targets.each do |target|
#       target.build_configurations.each do |build_configuration|
#         build_configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
#       end
#     end
#   end
# end



# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'QRiderRD' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
